### ISSUE TITLE
When increase zoom, the particules don't decrease size.

### ISSUE THREAD

**Issue by ricardomiguelfaria** [danwild/leaflet-velocity#1]
Hi,
i think is a bug in WindJS, because when you zoom the map, the particules should decrease size .
In your other project,  wind-js-leaflet, you don't have this problem.

**Comment by shymek1337** [comment]
yes is think the same way. but i think they decrease in width just not in length. it seems like the length is fix to a number in meter / km or similar no matter wich zoom level. I would like to use it, but im stil a beginner. it is a awesome library though!

**Comment by danwild** [comment]
Thanks guys, I'm aware of this and intend to release an update when I get a chance to look at this in more depth

**Comment by danwild** [comment]
Issue resolved by [8d22805](https://github.com/danwild/leaflet-velocity/commit/8d22805484a312f7f73968c38d3601359625482e).
