### ISSUE TITLE
Missing PR in new release ?

### ISSUE THREAD

**Issue by claustres** [danwild/leaflet-velocity#12]
Just tested the 1.2.0 NPM package and it does not seem to include this yet merged PR https://github.com/danwild/leaflet-velocity/pull/10, is it an error or do you plan to release a new version soon ?

Thanks

**Comment by danwild** [comment]
Hey @claustres, yep 1.2.0 was published prior to PR #10 - v1.2.1 contains PR #10.

Cheers,
Dan
