### ISSUE TITLE
Add this plugin to Leaflet plugins list?

### ISSUE THREAD

**Issue by ghybs** [danwild/leaflet-velocity#16]
Hi,

Very nice plugin!

I have not found it in the [Leaflet plugins list](http://leafletjs.com/plugins.html).
Please would you agree to add it to that list?

As I see no other plugin from you in the list, I prefer asking first.
You can submit a PR on https://github.com/Leaflet/Leaflet/blob/master/docs/plugins.md, or I can do it for you if you give me explicit permission.

**Comment by danwild** [comment]
Ah yes thanks for the reminder @ghybs, I had been meaning to do this - [PR submitted](https://github.com/Leaflet/Leaflet/pull/5861).
