### ISSUE TITLE
Let Mousemove reflect selected units

### ISSUE THREAD

**Issue by SFSailor** [danwild/leaflet-velocity#17]
Great plugin!

One thing, the "_onMouseMove" code hard-codes m/s as the speed indicator.  Could we get that to reflect the speed units selected for the layer?

I tried to override the event handler, but my skills are weak. I could rewrite that part of the module, but that's bad practice...

**Comment by danwild** [comment]
Thanks, fixed in [cd565bd](https://github.com/danwild/leaflet-velocity/commit/519341188349f445252f4c6147b5e4944816ad99).
