### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by harksin** [danwild/leaflet-velocity#2]
hello, 
thank for this great library.
do you plan to add typings for this project ? (https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by danwild** [comment]
Hi @harksin, I haven't touched ts for a while so no immediate plans to add typings file.
However; feel free to submit a PR if you'd like to add one.

**Comment by chriswilley** [comment]
If you're incorporating this into an Angular2 project, you can create a file called leaflet.velocity.d.ts in src/typings/. Paste the following into that file:
```
declare namespace L {
    export function velocityLayer(options?: any): any;
}
```
Then in your component you can `import 'leaflet-velocity';` and do something like:
```
let vLayer = L.velocityLayer({
    displayValues: true,
    ...
});
```
This is working in a project I'm developing. Good luck!

**Comment by landru29** [comment]
How do you display `vLayer` in your angular2 project ?

**Comment by landru29** [comment]
Finally, I found:
In HTML:
```
<yaga-map ... #myMap></yaga-map>
```

In ts:
```
import { Component, AfterViewInit, ViewChild } from '@angular/core';
import { MapComponent as YagaMapComponent } from '@yaga/leaflet-ng2';
...
@Component(...)
export class MyComponent implements AfterViewInit {
  @ViewChild('myMap')
  public myMap: YagaMapComponent;

  ngAfterViewInit() {
   const vLayer = L.velocityLayer({
      displayValues: true,
      data: ...
    });
   this.myMap.addLayer(vLayer);
  }
}
```
