### ISSUE TITLE
$ not found

### ISSUE THREAD

**Issue by dceejay** [danwild/leaflet-velocity#24]
In my app I don't have jquery installed - so I get an error

    leaflet-velocity.min.js:formatted:150 Uncaught ReferenceError: $ is not defined
        at e._onMouseMove (leaflet-velocity.min.js:formatted:150)

Which I guess is coming from Line 85 of L.Control.Velocity.js
I guess maybe a `if (window.jQuery) {` would help - but not being a user of jquery...

**Comment by keul** [comment]
Had the same issue:

https://github.com/danwild/leaflet-velocity/blob/519341188349f445252f4c6147b5e4944816ad99/src/js/L.Control.Velocity.js#L85:L87

Seems that leaflet-velocity has a not-explicit jQuery dependency just for a small behavior:

1. removing jQuery usage should be easy (few JavaScript DOM calls like `if (self._container.previousElementSibling !== null {`)
2. At the same time this code seems used only for compatibility with another plugin not provided by leaflet or this library. I guess it's *leaflet-control-mouseposition*.
