### ISSUE TITLE
Inverse Y axis animation

### ISSUE THREAD

**Issue by karigarweb** [danwild/leaflet-velocity#25]
When we get sub-region data for wind for example:

`leftlon: -40,
rightlon: -30,
toplat: 40,
bottomlat: 30`

The rendered wind animations shows on wrong points for y axis. Have a look at attached wind json file using above bounds:

[2018070512.txt](https://github.com/danwild/leaflet-velocity/files/2168027/2018070512.txt)

----
Upon further investigation, I found out the issue is related to Scan mode. Leaflet Velocity works with Scan mode 0 only while the sub-region data is rendered in scan mode 64

**Comment by crimemrgogo** [comment]
Facing similar issue. Were you able to solve it?

**Comment by andressr-netmind** [comment]
Same issue
