### ISSUE TITLE
Update function?

### ISSUE THREAD

**Issue by prasanjitdash** [danwild/leaflet-velocity#32]
Hi Folks,

Does leaflet-velocity have an Update function?

For example, if I externally change the values of the optional parameters (minVelocity, maxVelocity, velocityScale, colorScale), is it possible to dynamically update the display using an update function? Or one has to completely reload?

Thanks for this useful API. Its a gift to the leaflet users.

**Comment by danwild** [comment]
Hi 👋

[setOptions](https://github.com/danwild/leaflet-velocity#public-methods) was added in https://github.com/danwild/leaflet-velocity/commit/6b9ca4370f198965fdf6f9b3bd0f5ff1b8d5c189
