### ISSUE TITLE
how to add winlayer overlay( on top) over temperature data?

### ISSUE THREAD

**Issue by shinnobi** [danwild/leaflet-velocity#36]
i seen this
https://earth.nullschool.net/#current/wind/surface/level/overlay=temp/orthographic=84.40,10.30,431/loc=90.698,5.106

i have already add temperature layer and i want add windlayer overlay over this temperature layer
but it when i add windlayer it always botoom 

$.getJSON('wind-global.json', function (data) {

                var velocityLayer = L.velocityLayer({
                    displayValues: true,
                    displayOptions: {
                        velocityType: 'Global Wind',
                        displayPosition: 'bottomleft',
                        displayEmptyString: 'No wind data'
                    },
                    data: data,
                    maxVelocity: 15,  
                })
                layerControl.addOverlay(velocityLayer, 'Wind - Global');

            })

i need some help

**Comment by quai20** [comment]
How do you add your temperature layer ? Can't you play with opacity ? That's what I do (example here :
 [https://user-images.githubusercontent.com/17851004/58861264-474a6480-86ae-11e9-8f4f-625c98404154.png](https://user-images.githubusercontent.com/17851004/58861264-474a6480-86ae-11e9-8f4f-625c98404154.png))

**Comment by shinnobi** [comment]
![Screenshot from 2019-06-04 15-05-36](https://user-images.githubusercontent.com/21121259/58862197-55ae7580-86da-11e9-904b-ea05a99521bb.png)
> How do you add your temperature layer ? Can't you play with opacity ? That's what I do (example here :
> https://user-images.githubusercontent.com/17851004/58861264-474a6480-86ae-11e9-8f4f-625c98404154.png)
nice bro, i add temperature layer by other project , but just simple by add normal leaflet layer
var layerControl = L.control.layers(null, {
            "temperature": bandsWindLayer,
        }).addTo(map);
And about opacity if i set it to value less than 1, it's not beautiful

**Comment by ColgateShu** [comment]
Hey bro @shinnobi  , can i know which project u're using? thx a lot!

**Comment by shinnobi** [comment]
> Hey bro @shinnobi , can i know which project u're using? thx a lot!

i using d3js
p/s by move temperature layer to bottomless it work

**Comment by ColgateShu** [comment]
> i using d3js
> p/s by move temperature layer to bottomless it work

What is the layer link you are using defined `bandsWindLayer` above?

**Comment by AmirFarhan** [comment]
> How do you add your temperature layer ? Can't you play with opacity ? That's what I do (example here :
> https://user-images.githubusercontent.com/17851004/58861264-474a6480-86ae-11e9-8f4f-625c98404154.png)

How do you play with opacity? @quai20

**Comment by quai20** [comment]
Hey @AmirFarhan , I load a temperature from WMS so in my case I use the opacity option from L.tileLayer.wms : 
`var wmsLayer0 = L.tileLayer.wms('http://nrt.cmems-du.eu/thredds/wms/METOFFICE-GLO-SST-L4-NRT-OBS-SST-V2?', {
   layers: 'analysed_sst',
   opacity: 0.35,
   colorscalerange: '270.0,305.0',
   abovemaxcolor: "extend",
   belowmincolor: "extend",
   numcolorbands: 30,
   time: yyyy+'-'+mm+'-'+dd+'T12:00:00.000Z',
   styles: 'boxfill/rainbow'
});`

**Comment by AmirFarhan** [comment]
Thank you @quai20 . At the moment, I'm having trouble with finding wms data for temperature. Do you have any suggestions on where to look at?

**Comment by quai20** [comment]
@AmirFarhan It depends what do you want to plot. For sea temperature, go look at http://marine.copernicus.eu. Plenty of products, most of them with WMS feature.
