### ISSUE TITLE
How to run the demo

### ISSUE THREAD

**Issue by AmirFarhan** [danwild/leaflet-velocity#39]
Tried running using the demo files but the only things I see are the satellite map and the grey map

**Comment by quai20** [comment]
Any log/errors in the console ?

**Comment by AmirFarhan** [comment]
I used an npm package called "http-server" to run the demo on a localhost server and as I stated before, the wind visualization is not visible. In the error messages it seems like it's running on jquery version 2.2.4 while on my dependency it is 3.4.1. Do I need the wind-js-server to just run the demo?

<img width="1280" alt="Screen Shot 2019-09-05 at 3 45 46 PM" src="https://user-images.githubusercontent.com/43822065/64321993-3f26fb80-cff4-11e9-910d-f8601cc80bc8.png">

**Comment by quai20** [comment]
If you downloaded/cloned the repo, try copying "dist" directory in the "demo" directory and change the path in demo.html (../dist/leaflet-xxxx -> dist/leaflet-xxxx). I remember having some issues with the relative path. 
I use "caddy" as a web server

**Comment by AmirFarhan** [comment]
Thank you @quai20 . That fixed it. However, when it is running, the overlay I have is "Wind-Global". The water and wind at GBR are not available. Do you have any idea what is going on?

**Comment by AmirFarhan** [comment]
Thank you @quai20 . That fixed it.

**Comment by estamos** [comment]
> If you downloaded/cloned the repo, try copying "dist" directory in the "demo" directory and change the path in demo.html (../dist/leaflet-xxxx -> dist/leaflet-xxxx). I remember having some issues with the relative path.
> I use "caddy" as a web server

Could you give me some info on how to set on caddy and run demo ?
I have already download the repo, copied `dist` directory in the `demo` and changed the path in `demo.html `.
I am using `v2.1.1 => /private/tmp/caddy-20200823-12564-1btzrty/caddy-2.1.1` on macOS Big Sur v11.0 Beta (20A5354i) .

**Comment by quai20** [comment]
> > If you downloaded/cloned the repo, try copying "dist" directory in the "demo" directory and change the path in demo.html (../dist/leaflet-xxxx -> dist/leaflet-xxxx). I remember having some issues with the relative path.
> > I use "caddy" as a web server
> 
> Could you give me some info on how to set on caddy and run demo ?
> I have already download the repo, copied `dist` directory in the `demo` and changed the path in `demo.html `.
> I am using `v2.1.1 => /private/tmp/caddy-20200823-12564-1btzrty/caddy-2.1.1` on macOS Big Sur v11.0 Beta (20A5354i) .

Hi @estamos , do you have caddy working ? If so, just go to the demo directory and launch a web server (https://caddyserver.com/docs/getting-started)

**Comment by mylesmc123** [comment]
I wanted to re-visit this issue, as I'm having trouble getting to demo to run. Its surely just user error, but any help would be appreciated.

I am running from VS Code in Debian Linux (Mint 20) and have tried a few things to get up and running:

- Used Git Clone to get a copy of the GitHub repository.

- Copied the ./dist folder in ./demo/dist.

- Updated demo.html:

`

<!doctype html>
<html>
<head>
	<title>LeafletVelocity Demo</title>
	<meta charset="utf-8">
</head>
<body>

<div id="map"></div>


<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<link rel="stylesheet" href="https://npmcdn.com/leaflet@1.1.0/dist/leaflet.css" />
<script src="https://npmcdn.com/leaflet@1.1.0/dist/leaflet.js"></script>


<link rel="stylesheet" href="/dist/leaflet-velocity.css" />
<script src="/dist/leaflet-velocity.js"></script>


<link rel="stylesheet" href="demo.css" />
<script src="demo.js"></script>

</body>
</html>` 

- Installed Caddy

- Created Caddyfile and placed in a clone of the Git Repo's root directory:

`:2015 {
    root * /demo
}`

- Started Caddy web server in the Root directory.

- From root directory run: `npm run watch'.

The result of this sequence just produces an empty page. Can you offer any guidance on getting the demo loaded to the Caddy web server properly?

**Comment by mylesmc123** [comment]
Got it by changing moving the Caddyfile the demo directory and changing the Caddyfile to: 
```
:2015 {
    file_server browse
}
```
