### ISSUE TITLE
is there any way we can create wind layer as tile layer?

### ISSUE THREAD

**Issue by chakravarthi-vl** [danwild/leaflet-velocity#45]

**Comment by brentfraser** [comment]
As a standard image tile, no.  Currently the velocity data is delivered as a single JSON file of locations, direction and magnitude (well really U,V components of the vector).  The animated arrows are then calculated and rendered onto a canvas element.

 Using vector tiles might be possible.  Or maybe using some other OGC compliant spatial data transfer format.

Why do you want to use tiles?

**Comment by chakravarthi-vl** [comment]
Hi brentfraser thanks for replay,

I want to build windy like application, When I inspected there are loading as tile's, Do you any idea what the tools they are using for heatmap and wind display.

**Comment by brentfraser** [comment]
If you mean Windy.com, they use a variety of web mapping techniques.  No, I do not know the tools they are using.

**Comment by danwild** [comment]
Windy also appears to use a single canvas for velocity rendering, and tiled canvases for the scalar heatmap (e.g. temp).

Tiling of canvas for velocity rendering is not supported by `leaflet-velocity`, and there are no plans to do so.
