### ISSUE TITLE
Weather for a region is not positioned correcly

### ISSUE THREAD

**Issue by turban** [danwild/leaflet-velocity#46]
Thanks for a great plugin! 

I've created wind data for a region and added to a Leaflet map using this plugin:
http://mastermaps.com/racetracker/hardangervidda.html

I'm reading the bounds from the JSON-file and they are correct when I draw a rectangle and zoom the map to these bounds. The wind layer is displayed below the correct position: 

<img width="862" alt="Screenshot 2020-03-07 at 16 34 00" src="https://user-images.githubusercontent.com/548708/76146252-7e143780-6091-11ea-9b2b-6128f1300f1c.png">

Is this a know issue?

**Comment by brentfraser** [comment]
The problem is the "scanMode" in the json (and grib) file.  Currently only scanMode: 0 is supported.  
If your scanMode: 64, a quick fix is to modify the json file to set "dy": -0.25 so the Y direction is incremented in the opposite direction.

A better fix is to modify the leaflet-velocity JavaScript to interpret the scanMode and adjust the parameters appropriately (and maybe just support a subset of scanModes).  For example, around line 530:
if (header.scanMode === 64)  Δφ = -Δφ;

But really we should decode the scanMode bits and give a message for those we don't support.

**Comment by brentfraser** [comment]
FYI. some links
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-4.shtml
https://www.unidata.ucar.edu/mailing_lists/archives/netcdf-java/2015/msg00001.html
https://trac.osgeo.org/gdal/ticket/2550

**Comment by brentfraser** [comment]
A slightly better (but not tested) fix, at line 530:

```
    
    var scanModeMask = header.scanMode.toString(2)
    scanModeMask = ('0'+scanModeMask).slice(-8);
    var scanModeMaskArray = scanModeMask.split('').map(Number).map(Boolean);
    var supported = true;	
    if (scanModeMaskArray[0]) Δλ =-Δλ;
    if (scanModeMaskArray[1]) Δφ = -Δφ;
    if (scanModeMaskArray[2]) supported = false;
    if (scanModeMaskArray[3]) supported = false;
    if (scanModeMaskArray[4]) supported = false;
    if (scanModeMaskArray[5]) supported = false;
    if (scanModeMaskArray[6]) supported = false;
    if (scanModeMaskArray[7]) supported = false;
    if (!supported) console.log("Data with scanMode: "+header.scanMode+ " is not supported.");

```

**Comment by d03090** [comment]
Thank you very much for this solution! I was struggling with this scanMode as well. So, this worked fine for me!

Still not exactly sure why scanMode 64 (`01000000`) affects Bit No. 2 and not No. 7 though (why is this flipped?).

**Comment by brentfraser** [comment]
I think it is a LSB/MSB thing.  I guess I could reorder the scanModeMaskArray  in the above code to match the bits in the table https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-4.shtml

**Comment by turban** [comment]
Thanks @brentfraser! Your quick-fix solution worked :-)

**Comment by danwild** [comment]
Thanks @brentfraser, please consider putting in a PR.
