### ISSUE TITLE
How turn off animation?

### ISSUE THREAD

**Issue by leoGrg** [danwild/leaflet-velocity#50]
Hi,

I currently use **_clearWind()** to stop the animation but it restarts when I zoom on the leaflet map.
The goal would be to have an on/off button on the map.

`function clearAppWind() {
      _self._mapService.particles_layer._clearWind();
    }
    function startAppWind() {
      _self._mapService.particles_layer._startWindy();
    }
    myMap.on('zoomstart', clearAppWind);
    myMap.on('movestart', clearAppWind);
    myMap.on('zoomend', startAppWind);
    myMap.on('moveend', startAppWind);`

**Comment by brentfraser** [comment]
I think I would use 
`map.addLayer(myVelocityLayer);`
and
`map.removeLayer(myVelocityLayer):`
with your button events.

Or just use Leaflet's Layer Control: https://leafletjs.com/reference-1.6.0.html#control-layers

**Comment by leoGrg** [comment]
Thank you for your answer, 
Yes I already apply this method for my button events.
But when I zoom on the map, wind animations automatically reactivated.

**Comment by brentfraser** [comment]
I tested using Leaflet's Layer control, and with ToolBar2 with 2 buttons (add,remove) and could not reproduce your issue.  In both test cases the velocity layer stayed on (or off)  when the map was zoomed.

**Comment by danwild** [comment]
@brentfraser is correct, to disable animation you simply remove the layer from the map.

If you are still seeing animations, I suspect you have not removed the layer from the map correctly.
