### ISSUE TITLE
Use of AddVelocity() in leaflet.extras2 in R 

### ISSUE THREAD

**Issue by cookalex77** [danwild/leaflet-velocity#52]
Hi, I am trying to use the AddVelocity function in the leaflet.extras2 package in R so that I can add wind velocity visualization data to my leaflet map. I have found JSON u and v wind data from NOAA, but I cant seem to successfully add my wind velocity data using the content=. Any suggestions on how to format the json data so that AddVelocity can process it into an animation? The code below runs in R, but no wind arrows or animation is produced. Any help would be much appreciated! 

content<-"https://pae-paha.pacioos.hawaii.edu/erddap/griddap/ncep_global.json?ugrd10m%5B(2020-06-16T12:00:00Z)%5D%5B(-23.5):(80.0)%5D%5B(219.0):(323.5)%5D&.draw=surface&.vars=longitude%7Clatitude%7Cugrd10m&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff"

leaflet() %>%
  addTiles(group = "base") %>%
  setView(-71,42,5) %>%
  leaflet.extras2::addVelocity(content =content ,group = "velo", layerId = "veloid")

Site with wind data :https://pae-paha.pacioos.hawaii.edu/erddap/griddap/ncep_global.graph?tmpsfc[(2011-05-07T00:00:00Z)][(34.625):(46.875)][(283.125):(295.375)],tmp2m[(2011-05-07T00:00:00Z)][(34.625):(46.875)][(283.125):(295.375)]&.draw=vectors&.vars=longitude%7Clatitude%7Ctmpsfc%7Ctmp2m&.color=0x000000&.bgColor=0xffccccff

**Comment by brentfraser** [comment]
Have a look at https://github.com/danwild/wind-js-server
Especially the app.js for a good source of wind data (https://nomads.ncep.noaa.gov/)

**Comment by cookalex77** [comment]
Thanks so much for your response! I have looked at the other wind-js pages, however I am using Program R, not a java script to try and create my map. Using a function called addVelocity in this R package https://cran.r-project.org/web/packages/leaflet.extras2/leaflet.extras2.pdf. Do you have any advice or knowledge on the leaflet functions in R?

**Comment by brentfraser** [comment]
I recommend getting the demo data working with your setup just to confirm the R- Leaflet-velocity connection is working.

**Comment by cookalex77** [comment]
Thanks for your help and suggestions. The addVelocity function in R does work with the demo data. But I have been unsuccessful in formatting my wind data (downloaded from the previously posted website, or downloaded from the rWind package in R) into the correct structure in the json file for it to work with the velocity function.  Is there any info on how the demo data is formatted, or what components/data points leaflet-velocity needs to produce wind arrows. I have lat/long, wind speed, wind direction and u and v components in 50km grid format for my geographic region of interest. Thanks!

**Comment by brentfraser** [comment]
This leaflet-velocity plugin for Leaflet uses a very specific (and rare) format of vector data.  To some extent it is a JSON fomat of the binary [GRIB2 WMO format](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/) of GFS data generated by [NOAA's NCEP](https://nomads.ncep.noaa.gov/).  

Have a look in the demo .JSON file in the [demo folder ](https://github.com/danwild/leaflet-velocity/tree/master/demo).  The wind-gbr.json file is the simplest example: it has two components U, V of wind.  Each component is in a JSON object with a header section and data section.  The header names are from the GRIB format mentioned above.
