### ISSUE TITLE
Project still working?

### ISSUE THREAD

**Issue by ToninoTarsi** [danwild/leaflet-velocity#59]
I just downloaded and I was testing it with the demo project.
I have no wind vectors even if the data are read correctly.
Same in the Live Demo here: https://danwild.github.io/leaflet-velocity/
Is this project still working?
Thanks for info
Tony

**Comment by brentfraser** [comment]
The demo works fine (I just tried with Firefox and Chrome), but you do need to use the Layer control button in the upper right of the map to turn on the layers.

**Comment by ToninoTarsi** [comment]
> 
> 
> The demo works fine (I just tried with Firefox and Chrome), but you do need to use the Layer control button in the upper right of the map to turn on the layers.

Thank you verry much :-) for your hint . I was struggling with it. Sorry and thanks..
