### ISSUE TITLE
leaflet-velocity does not update from wind-js-server

### ISSUE THREAD

**Issue by TheDoebert** [danwild/leaflet-velocity#66]
Great project but I need a little help. 
When running demo.html in firefox and selecting wind-global the wind pattern is always the same.
No errors in console when running npm in leaflet-velocity or wind-js-server.
XML Parsing Error: syntax error for wind-global.json Line Number 1, Column 1 in firefox.
If I take the most recent json-data from wind-js-server & copy to demo folder in leaflet-velocity and rename it to wind-global.json the wind pattern is updated.
Running on windows 10 system.
I placed wind-js-server folder in the leaflet-velocity main directory.
I am guessing a path needs changed being I am using windows but don't know for sure.
Thanks and any help would be appreciated.

**Comment by LukePrior** [comment]
The example does not communicate with wind-js-server this functionality needs to be added by yourself.
